language: php

php:
  - 5.4
  - 5.5

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - pear channel-discover pear.phpmd.org
  - pear install phpmd/PHP_PMD
  - phpenv rehash

script: ant check

notifications:
  email:
    - lantian.ivan@gmail.com